name: Bug Report
description: File a bug report
body:
  - type: textarea
    id: summary
    attributes:
      label: Bug Summary
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: Reproduction Steps
      value: |
        1. [Step 1]
        2. [Step 2]
        3. [Step 3]

        Expected Behavior:

        Observed Behavior:
    validation:
     required: true
  - type: input
    id: ios-version
    attributes:
      label: iOS Version(s)
      placeholder: 15.1.3
    validations:
      required: false
  - type: input
    id: sdl-ios-version
    attributes:
      label: sdl_ios Version
      placeholder: 7.3.0
    validations:
      required: true
  - type: textarea
    id: testing-against
    attributes:
      label: Testing Environment(s)
      description: |
        For Example:
          - Ford TDK 3.4 (19286_DEVTEST)
          - Manticore v2.9.0 (See top of the open Manticore screen)
          - SDL Core v8.0.0 + Generic_HMI v0.11.0
      render: markdown
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy-paste any relevant log output. Attach any relevant crash reports or test apps as well.
      value: |
      ```
      ```
      
